name: Build and Deploy Angular with Docker

on:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image for tests
        run: docker build --target build -t angular-test .

      - name: Run unit tests inside Docker
        run: docker run --rm -e CHROME_BIN=/usr/bin/chromium angular-test npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox

      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=arthursalmin
            -Dsonar.projectKey=ArthurSalmin_angularHelloWorld
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=src/app/**/*.spec.ts \
            -Dsonar.exclusions=src/app/**/*.e2e.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t angular-app .

      - name: Run container and copy build files
        run: |
          docker run --rm --name angular-container -d angular-app
          docker cp angular-container:/usr/share/nginx/html dist
          docker stop angular-container

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.GH_TOKEN }}
          clean: true
